title: taylor's portfolio
subtitle: A Portfolio of taylor
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://taylor-jun.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Contact
      url : /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: taylor.JPG
author: taylor
author_bio: 안녕하세요. 좋은 개발자가 되고 싶은 이 준태입니다.
author_email: "taylor-jun@gmail.com"
author_location: Korea
author_website_url: "https://taylor-JuN.github.io"
typewrite-text: 안녕하세요. 준태의 포트폴리오 입니다.

# Experiences
author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

# Education
author_education_details:
              - college_logo: smu.jpg
                college_name: SMU
                college_url: https://smu.ac.kr
                college_degree: Computer science
                description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: projectthumb.png
                project_title: 코로나 취합검사법 최적화
                project_description: 코로나 취합검사법의 최적 검사수 제시 및 코로나에 대한 정보 제공 웹 어플리케이션
                project_url: https://github.com/taylor-JuN/DataCampus-team-Project
                visibility: true
              - project_thumbnail: projectthumb.png
                project_title: 웹 빌더
                project_description: 중계 플랫폼을 활용한 웹 빌더 웹 어플리케이션
                project_url: https://github.com/taylor-JuN/Spring-builder
                visibility: true
              - project_thumbnail: projectthumb.png
                project_title: 상병 코드를 활용한 합병증 정보
                project_description: 표본 코호트 데이터 베이스 및 상병 코드를 활용한 합병증 정보 제공하는 어플리케이션
                project_url: https://github.com/taylor-JuN/DataCampus-indi-Project
                visibility: true
              - project_thumbnail: sideprothumb.png
                project_title: 카페 레시피 맞추기
                project_description: 카페 아르바이트생을 위한 레시피 맞추기 게임
                project_url: https://github.com/taylor-JuN/Unix-Project1
                visibility: true
              - project_thumbnail: sideprothumb.png
                project_title: 스마트 오더
                project_description: 서버와 클라이언트를 통한 소켓 프로그래밍 프로젝트 
                project_url: https://github.com/taylor-JuN/Unix-Project2
                visibility: true


# social links
twitter_username: taylor
github_username:  taylor_JuN
facebook_username: taylor
linkedin_username: taylor
behance_username: taylor
instagram_username: taylor
medium_username: taylor
telegram_username: taylor
dribbble_username: taylor
flickr_username: taylor

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: taylor-JuN

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
